services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  config-server:
    build: ./config_server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      # make config import optional and point at the Docker service name
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - backend

  login-signup-microservice:
    build: ./login_signup_microservice
    container_name: login-signup-microservice
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL:      jdbc:mysql://mysql:3306/${MYSQL_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_CONFIG_IMPORT:       optional:configserver:http://config-server:8888
    networks:
      - backend

  chat-microservice:
    build: ./chat_microservice
    container_name: chat-microservice
    ports:
      - "8080:8080"
    depends_on:
      login-signup-microservice:
        condition: service_started
      notifs:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL:      jdbc:mysql://mysql:3306/${MYSQL_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_CONFIG_IMPORT:       optional:configserver:http://config-server:8888
    networks:
      - backend

  notifs:
    build: ./notifs
    container_name: notifs
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      login-signup-microservice:
        condition: service_started
      chat-microservice:
        condition: service_started
      notifs:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - backend

volumes:
  mysqldata:

networks:
  backend:
